### PR TITLE
Refactor/irc

### PR DESCRIPTION
**Pull request by Chronial**
This moves the IRC code into its own class, but also changes some logic:

* The IRC server does not block on read anymore
* Connections to nodes from IRC are made based on a priority sorting of all the known nodes

### CODE REVIEW

**Comment by Chronial** [comment]
:smiley:

**Comment by Chronial** [comment]
@Wulf2k Thanks for merging these massive PRs. If you have any questions at all regarding the code in these PRs, please feel free to ask anytime.

**Comment by Wulf2k** [comment]
I should be paying closer attention so that I fully understand all the code, but I'm getting the gist. You're doing good work, thanks for it all.

It really struck me that I should be paying more attention though when I saw that people were connecting to IRC with the GUID as a nick instead of their SteamID, and I didn't know why....

Just try not to do anything evil. =]

**Comment by Chronial** [comment]
> It really struck me that I should be paying more attention though when I saw that people were connecting to IRC with the GUID as a nick instead of their SteamID, and I didn't know why....

Yeah, sorry – I already thought that I should have mentioned that in the PR, but I forgot ^^. In case that wasn't clear:

The guid is just used as a way to get a random unique nick (if we care, I think we can make that prettier by using a shorter substring. We don't have enough nodes to require full guids). Random nicks are used because that is the only way to connect to IRC before Dark Souls is running, which seemed a useful feature to me.

> Just try not to do anything evil. =]

I'm trying :smile:

**Pull request merged**
