### PR TITLE
[Refactor] Move DS process communication into separate class

### PR DESCRIPTION
**Pull request by Chronial**

### CODE REVIEW

**Comment by Chronial** [comment]
If you like it, you should merge it fast, before you create any conflicting changes :). If you already did, push them to master and I will update this.

Next step would be to separate out the IRC code and improve it's multithreading, so the data flow is more constant.

**Comment by Wulf2k** [comment]
Looks good at a quick glance.

Likely merge soon.

**Comment by Wulf2k** [comment]
Don't really have time to test this thoroughly tonight, but it looks acceptable at a quick glance.

I'll merge it in and then poke at it more when I have time.

**Comment by Wulf2k** [comment]
Active nodes now only seem to fill in at a rate of one per 10 seconds instead of all at once.

Unrelated to this push, but the current .ICO file seems to be crashing Linux users.  I've put up a test EXE without it (non public, accessed by unpublished link only).  Will confirm when I hear back.

**Comment by Wulf2k** [comment]
11:50:35 PM: Error reporting status - Conversion from string "01100001009cd8ef" to type 'Boolean' is not valid.

Is reporting messed up?

Needs further testing.

**Comment by Chronial** [comment]
Nope, that error is caused by names that contain commas. You filter out the commas in our own name, but not in the names of other nodes.

**Comment by Wulf2k** [comment]
Good catch, I'll try fix that up tomorrow.

**Pull request merged**
