### PR TITLE
DarkSouls (auto)Start util

### PR DESCRIPTION
**Pull request by gpotter2**
Small auto start function added using direct steam path (works even if
"steam://" association is broken)

### CODE REVIEW

**Comment by Chronial** [comment]
It is very unexpected to just start dark souls when I start the tool, which will then also immediately lose focus. It would be cool if can do this without adding to the UI, but I don't think this is the right way.

**Comment by gpotter2** [comment]
> without adding to the UI

You mean without showing the DarkSouls window ?

**Comment by Chronial** [comment]
I meant without adding a checkbox.

**Comment by gpotter2** [comment]
So by what should it be started by ? I understand it's better to have a way to select rather you want to start it or not, but without adding it to the UI i don't really se how :/

**Comment by Chronial** [comment]
We could use a command line parameter, but I'm not sure whether that is what people would want.

**Comment by gpotter2** [comment]
Or we may replace one of the checkboxes by a sub "option" popup menu... so the main UI won't be overloaded

**Comment by Wulf2k** [comment]
It may be about time that we just created an options tab.

Tuck "Join DSCM-Net" under there.  Get rid of the Expand DSCM checkbox and
just save the window position/size in the registry whenever it gets
changed, with appropriate minimums.

Nobody start work on it until it's been properly discussed....

**Comment by Chronial** [comment]
> It may be about time that we just created an options tab.
> 
> Tuck "Join DSCM-Net" under there. Get rid of the Expand DSCM checkbox and just save the window position/size in the registry whenever it gets changed, with appropriate minimums.

I agree. I would not store window position, as restoring that is difficult (the position might not be on any monitor anymore).

I'm just a little worried that people might miss it if it's just a normal tab. Is it possible to make a tab right-aligned in the tab bar?

**Comment by Wulf2k** [comment]
Not that I'm aware of, but we could probably make the options tab size
large enough to fill up the rest of the space and fake right aligned.  I'm
not sure if that would look ugly, or fit nicely.

**Comment by Chronial** [comment]
I vote ugly ^^

**Comment by Chronial** [comment]
Ah, how about making it the first tab? Still have the active nodes tab selected by default, though.

**Comment by Wulf2k** [comment]
Options first, and defaulting to the second tab?

I guess that could work.

**Comment by gpotter2** [comment]
Yeah sounds great.

**Comment by Chronial** [comment]
If we are restructuring the UI, I would also propose some more changes. IMHO the main use of DSCM has shifted from manual connections to just automatically fixing DS Multiplayer. In consequence I would change the UI like this:
* As you said, remove "expand", and move "join dscm-net" to the options tab.
* Remove the nodes display in the top right and
   * Display number of active nodes in the active tab (like for dscm-net)
   * Make the maximum nodes a setting in the options, that is also remembered between restarts. Maybe also make it like PVP-Watchdog just a checkbox ("increase maxnodes")?
* Remove the favorites and recent tab and the target box + connect button from the top right and move all of that to a "manual" tab:
   * At the top we have The target box and the connect button
   * Beneath that in two rows the favorites and recent list. Or should we maybe remove the recent list? Is it still useful?

Now all that is left in the top UI is Update, Node Drawing and Your SteamId – that should all fit in one column. We could also move node drawing to settings and the steamid to manual.

What do you think?

**Comment by gpotter2** [comment]
> We could also move node drawing to settings

I guess this should be easily reachable, so it should stay where it is...

> Maybe also make it like PVP-Watchdog just a checkbox ("increase maxnodes")?

Might be easier to just select the number you want...

Otherwise all you say sounds great :smile:  !!

**Comment by Chronial** [comment]
> Might be easier to just select the number you want...
What is the benefit of that?

> I guess this should be easily reachable, so it should stay where it is...
We have the ctr+1 hotkey for that

**Comment by gpotter2** [comment]
> We have the ctr+1 hotkey for that

Ups that's right :smile: always forget about it...

> What is the benefit of that?

If you don't want to get too much lag (if your internet speed kinda suck as i do ^^), those kind of things...

**Comment by Wulf2k** [comment]
> What is the benefit of that?
Taking it right to 31 or 32 has some people report (or at least suspect) odd behaviour.

Manually setting it to 28 or something with a bit of a buffer could allow an increased node count without the suspected issues.

**Comment by Wulf2k** [comment]
The active node count can probably be removed and just tagged onto the label of the active nodes tab.

**Comment by gpotter2** [comment]
Should I close this thread ?

**Comment by Chronial** [comment]
>> What is the benefit of that?
>
> If you don't want to get too much lag (if your internet speed kinda suck as i do ^^), those kind of things.

I highly doubt that reducing the nodecount will reduce your lag. Does the connection to those nodes generate a relevant amount of traffic?

> Taking it right to 31 or 32 has some people report (or at least suspect) odd behaviour.
>
> Manually setting it to 28 or something with a bit of a buffer could allow an increased node count without the suspected issues.

But do more than 10 people actually know that? Without any guidance this seems to be useless to almost everybody.

> Should I close this thread then ? This discussion may be continued in a more relevent one :)

You can close this PR, and we can continue the discussion – now we started here, so … ^^

**Comment by gpotter2** [comment]
> To clarify: If you think that 28 is safer than 31, I suggest a dropdown – "default" "safe more" "maximum".

I agree with that.

**Comment by gpotter2** [comment]
I also think there should be a "steam beta remover function" to prompt a popup box to the player and ask him if he wants to disable dark souls beta if enabled, in order to use DSCM

That's not too hard to do

**Comment by Wulf2k** [comment]
> Edit: To clarify: If you think that 28 is safer than 31, I suggest a dropdown – "default" "safe more" "maximum".

What's the harm in allowing people to set it to anywhere within bounds?  If they want it at 10, go nuts, or maxed, feel free.  Seems to add extra complexity just to remove freedom from the user.

**Comment by Chronial** [comment]
> What's the harm in allowing people to set it to anywhere within bounds?  If they want it at 10, go nuts, or maxed, feel free.  Seems to add extra complexity just to remove freedom from the user.

My thinking is that most people just won't touch it since they just don't know what they should set it to. So the harm is that choice confuses users. I myself never really touched it in DSCM, because I was not sure what I should set it do and didn't feel like doing research for that – I just thought "The default is probably fine". I only changed it once I saw the binary option in watchdog with the short explanation.

But in the end this comes down to the question of who you want to serve – the masses or the enthusiasts. Since this is your project, that is also your choice :).

**Pull request closed without merging**
