### PR TITLE
Added support for plain steam names

### PR DESCRIPTION
**Pull request by gpotter2**
Added support for plain steam names
Example: i want to play with a guy whose username is "boby123". So i
just type "boby123".

### CODE REVIEW

**Comment by Wulf2k** [comment]
Isn't this exactly what you just submitted?

**Comment by gpotter2** [comment]
Uh, kind of, but Chronial told me to close the request and modified many things to make it cleaner, but he didn't really added the function i was thinking about...

**Comment by Chronial** [comment]
No, this actually does not work. eur0pa is just one of the few examples where it works. Random counterexample:
http://steamcommunity.com/profiles/76561198086629378/
http://steamcommunity.com/id/Heiji201

**Comment by gpotter2** [comment]
Ok then.

**Comment by Chronial** [comment]
Don't take this as an disinterest in contributions. I really liked the idea and was actually implementing it as part of #74 until I noticed that it doesn't work.

**Pull request closed without merging**
