### PR TITLE
Handle profile urls that contain the SteamID

### PR DESCRIPTION
**Pull request by Chronial**
This allows pasting full profile URLs into the text box. Makes adding people from the group chat a bit easier.

### CODE REVIEW

**Comment by Chronial** [comment]
thx, that was fast :)

**Comment by Wulf2k** [comment]
I'd have been done sooner, but I had to brush up on my regexing and make sure it did what it looked like it should =]

**Comment by Wulf2k** [comment]
Hopefully the need to add random people by their profile URL will be much lower by the next version.

I'll be adding in basic IRC functionality so that DSCM can form its own botnet and auto-matchmake.

**Comment by Chronial** [comment]
Read about your plans on the reddit. Let's see whether your server will be more stable than the steam matchmaking ;).

**Comment by Wulf2k** [comment]
Honestly, it can't be worse...

My only potential concern is that I'm underestimating DSCM's popularity and may in fact be building a DDoS botnet pointed at my own server.  I'm pointing it at a subdomain that I can point elsewhere if the load gets too big though.  As long as I can make the client fail gracefully if they all nuke the sever then it should be good while I sort that part out.

I think I'll make a smaller release before that one, with a quick Favorites/Recent tab to try auto-matchmaking off of first.  If it remembers 10 of the most recent nodes and then 10 user-selected favorites, I'd hope that at least one of those would be online to connect to automatically and fix people's 0 nodes issues on start.

Anyway, as for the stable part, as long as I can handle the (hopefully) minimal load of an IRC server then I plan on having the clients handle the actual matchmaking itself.  Give a few checkboxes so they can either connect to anybody or filter things down a bit and it should work out rather well.

...Then from there I can start taking things too far and look into summoning via right click instead of in-game summon signs.

So many ideas, so little time.

**Comment by Chronial** [comment]
Do you know whether the steam matchmaking is random or tries to find people near you with similar levels?

**Comment by Wulf2k** [comment]
A bit of both.

This is purely speculation, but I "think" there are two matchmaking processes going on.  One that just tries to add anybody, and another that will try to prune the list of less appealing nodes and find new ones in an appropriate range.

I don't have a full understanding of the matchmaking system though, just the very specific bits that I've looked into. 

One of these days I should just set a breakpoint on the steam_api.dll's networking functions and see which parts of the game are calling it from a fresh start.

**Pull request merged**
