### PR TITLE
Replace IRC with http service

### PR DESCRIPTION
**Pull request by Chronial**
This replaces the IRC server with a http service. The server code is here: https://github.com/Chronial/dscm-server

That server will also load nodes from IRC and publish nodes to IRC, so we can have a smooth transition.

The server will still just collect all nodes and send the list to all clients. But lack of IRC overhead and gzip compression already make this a lot more efficient

@Wulf2k It would be good if you could get this into a testing release as soon as possible.

### CODE REVIEW

**Comment by Wulf2k** [comment]
Awesome, but i don't have time to test it tonight.  Do you feel confident
enough in the code for me to just merge it, compile it and upload it?

**Comment by Wulf2k** [comment]
And I just wasted more time by introducing conflicts into this one by merging the old one....

**Comment by Chronial** [comment]
I will have a look and resolve them.

**Comment by Wulf2k** [comment]
k, I was just about to release a separate compile of just PR #98 .  

I'll hold off then, and sorry about screwing it up.  I should really just "learn" Github one of these days.

**Comment by Chronial** [comment]
Alright, conflicts are resolved. I tested it again just in case, and everything looks fine.

**Pull request merged**
