### PR TITLE
Added friend detection

### PR DESCRIPTION
**Pull request by gpotter2**
I was asking myself about how to play with friends if the steamID option was removed, that's why i added a small function to get the user's friends and order them on top inside the nodes chooser...

Added a friend detection system used to select the nodes.

If I did anything wrong, just tell me :)

### CODE REVIEW

**Comment by Wulf2k** [comment]
I'm a little hesitant about this as it won't work if people use their privacy settings.

For example, I can't test it.

I also won't be able to take a closer look at it for another few days, heading out for the weekend.  I'll take a look when I'm back.

Chronial, any input?  Are your privacy settings open enough to test it?

**Comment by Chronial** [comment]
This has similar issues as #55.

* Just because I'm steam-friends with someone doesn't mean they are a good node. You are smarter about this and at least only connect to people that are in coop level range. But they still might be at the other end of the world.
* I also just might just have added random people to my friends, or maybe just people I really don't like so I remember their names. Friends list does not mean "want to play with".
* This goes very clearly against the Dark Souls multiplayer spirit. Your lack of control is very much part of the game. DSCM of course goes against this a little bit by allowing manual connections to people, but my understanding is that this is meant for only two things (@Wulf2k correct me on this):
  * Having that coop sessions with your buddy. Manual connection is fine for that
  * As a workaround until automatic connections are good enough
* A frequent complaint on the forums about DS is that they keep connecting to / invading the same people – this would make it worse.

Because of this, I don't think adding a hidden feature like this is a good idea.

The other issue with this is of course that will only work for some others due to privacy settings. I don't like the idea of having features like that.

In my opinion this feature could have some merit if you add a new tab that requires the player to log in and that then displays the friends list and maybe also displays a checkbox `autoconnect to friends`, or even better one checkbox per friend. That could IMHO also replace the favorites tab.

@Wulf2k What's your opinion on that?

**Comment by Wulf2k** [comment]
>     Having that coop sessions with your buddy. Manual connection is fine for that
>    As a workaround until automatic connections are good enough

Pretty much.

I always want DSCM to allow you to sit down and play with a specific friend without 20 minutes of voodoo magic to get yourself added as their node the "intended" way, but beyond that, the automatic stuff should be more or less random.

Chronial seems to take that mantra to heart more than I do, but I still agree.

> In my opinion this feature could have some merit if you add a new tab that requires the player to log in 

DSCM doesn't want your passwords.  Never type your password into DSCM.  The second that becomes a normal thing to do, forks will either pop up to steal passwords or people will claim that DSCM is responsible for their account getting shut down.  Passwords bad.  No passwords.  Icky.  Ptooie.

I think manually double clicking on favorites is good enough.

If you want to connect with friends, add them as a favorite once and then double click them.

**Comment by gpotter2** [comment]
I'm going to do some research if it's not possible to parse the friends directly from the steam app... But all of you are right, this needs improvment... I guess a "connect to steam friend" button somewhere would be a quite good alternative

**Comment by Chronial** [comment]
> parse the friends directly from the steam app

Be aware that unlike Dark Souls, the steam app is frequently updated.

**Comment by Wulf2k** [comment]
Pulling it from the Steam app could be done through calls to the
steam_api.dll in the Dark Souls folder/memory.

I'm not sure ehat to do with that info once you have it though.  As you
said, just because they're friends doesn't mean you want to be connected.

**Comment by gpotter2** [comment]
> they're friends doesn't mean you want to be connected.

Sure, but you might want to select from like your friend list the one(s) you want to be connected with right now

**Comment by hydra-chan** [comment]
It sounds like this would work best like an extra, modified "Favourites" tab that automatically populates with friends who plays DS.

I think it's worth noting that Steam's actual way of displaying "Friends who play X" lacks customizable sorting, which could easily be applied within DSCM.

That said, as Wulf mentioned, it really only takes a couple clicks to play with a friend that you actually want to play with. I think it would work out to add it in as an extra tab.

**Pull request closed without merging**
